### ISSUE TITLE
[dev.icinga.com #11974] URL /nagvis/show/map was not found on this server.

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-nagvis#13]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11974

**Created by gbranko on 2016-06-17 13:28:29 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-06-17 13:28:29 +00:00 (in Redmine)_

---

Hi,

I was trying to integrate nagvis (1.8.5) into icingaweb2 (2.3.2) using icingaweb2-module-nagvis (git master snapshot).
Icingaweb2 works, also "standalone" nagvis works.
Authentication modules integrated by this plugin also work for me (when I got it to show up via some server side redirections).

I was following this guide https://exchange.icinga.org/icinga/NagVis also I applied few "fixes" I found on this bug tracker:
https://dev.icinga.org/issues/11457
https://dev.icinga.org/issues/10832

But when I click on "Map" on left side menu in icinga web2 I still get:
URL /nagvis/show/map was not found on this server.

Module inside icingaweb2 is enabled.

Also I have another question regarding this integration, is there something specific which needs to be configured to tell this module where nagvis is, or is there some location it expects to be installed in?

Regards,
Branko

**Comment by gbranko** [comment]
Hello,

This issue can be closed, this is not a bug in icingaweb2 or icingaweb2-module-nagvis.
The issue has been resolved and is related to the server configuration.
icingaweb2 was on the server root (not icingaweb2/ and nagvis was on /nagvis, and it for sure doesn't contain or handle  /nagvis/show/map).

Regards,
Branko

**Comment by lazyfrosch** [comment]
@gbranko thanks for feedback :)

**Comment by odrino14** [comment]
hi @gbranko can u tell me how i can fix this ?

**Comment by NotAProfessionalDeveloper** [comment]
Yep I would like to know too what that the actual problem and fix.
It's disgusting to see people asking for help and consuming resources, yet when they find a fix they don't even say how they fixed it.

**Comment by gbranko** [comment]
@odrino14 @NotAProfessionalDeveloper 

Hi, 

I haven't used this profile for a long time.

As describe the issue was on my end, and with server configuration.

icinga was "listening" on server '**/**' of the domain used, and Nagvis (application) was installed with an alias on the webserver **/nagvis**

icinga module which integrates nagvis ( _icingaweb2-module-nagvis_ ) is also **icinga.domain/nagvis** (as part of the icingaweb2 application)  as well as nagvis application, so the call ended on the nagvis application not module.

As an ugly workaround I changed nagvis application alias to be something else and changed **_icingaweb2-module-nagvis_**:
**_application/controllers/ShowController.php_** to point to it:
```
...
$baseurl = $this->Config()->get('global', 'baseurl', '/nagvis_app');
...
```

This is just an example which I remember from before, probably not recommended, there should be better options to solve this problem.

Regards,
Branko

**Comment by NotAProfessionalDeveloper** [comment]
Thanks a lot for the feedback!

Yeah I see, by default the Nagvis integration/module endpoint for Icingaweb2 is usually not in the root of the webserver, i.e. it is usually something like "/icingaweb2/nagvis".

Now if you configure a virtualhost, say icinga.example.com, with Icingaweb2 directly accessible at "/" then the module endpoint becomes "/nagvis".

Of course this conflicts with Nagvis being made accessible by the webserver at the same path "/nagvis" using an "Alias" (Apache), so that request never reaches Icingaweb2.

I'm not sure there are easy fixes. You can't have two things listening at the same URL.
Either you have to fiddle with mod_rewrite and target specific URLs/subpaths to be sent to the corresponding app.
Or you have to change one of them (the module endpoint URL, or the app) as you have done.

BTW integration of PNP4Nagios works just nice. But the endpoint ("/pnp") and the usual path for the app ("/pnp4nagios") don't conflict. However they also allow you to set the endpoint URL in the GUI, which Nagvis module does not.

Well, maybe we can come up with something and propose an enhancement ;)

**Comment by NotAProfessionalDeveloper** [comment]
Besides "ShowController.php"  you also have to update /opt/nagvis/etc/nagvis.ini.php:
```
[paths]
htmlbase="/nagvis-app"
```
